apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    agent: Rogan Letter Writer
    environment: staging
    managed-by: caminu
  name: Rogan Letter Writer-staging
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: staging
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openai-api-key
        - name: OPENAI_MAX_CONNECTIONS
          value: "8"
        - name: OPENAI_MAX_KEEPALIVE_CONNECTIONS
          value: "4"
        - name: PYTHONOPTIMIZE
          value: "1"
        image: us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/caminu-agents/${PROJECT_ID}/Rogan
          Letter Writer:${IMAGE_TAG}
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '2'
            memory: 1Gi
      serviceAccountName: Rogan Letter Writer-sa
